insert into sys_full_text_index (id, attribute, weight, object_id, class_id, body) values (1, 'content', 5, 20, 100,'wow wow база данных wow wow база данных wow wow база данных wow wow база данных wow wow база данных')
insert into sys_full_text_index (id, attribute, weight, object_id, class_id, body) values (2, 'title', 10, 20, 100,'wow wow')
insert into sys_full_text_index (id, attribute, weight, object_id, class_id, body) values (3, 'content', 5, 21, 110,'DBMS stands for DataBase ... wow')
insert into sys_full_text_index (id, attribute, weight, object_id, class_id, body) values (4, 'content', 5, 22, 110,'After you went through a ...')
insert into sys_full_text_index (id, attribute, weight, object_id, class_id, body) values (5, 'content', 5, 23, 110,'In this tutorial we will show ...')
insert into sys_full_text_index (id, attribute, weight, object_id, class_id, body) values (6, 'content', 5, 24, 110,'1. Never run mysqld as root. 2. ...restrict')
insert into sys_full_text_index (id, attribute, weight, object_id, class_id, body) values (7, 'content', 5, 25, 110,'In the following database comparison ... restrict')
insert into sys_full_text_index (id, attribute, weight, object_id, class_id, body) values (8, 'content', 5, 26, 100,'When configured properly, MySQL ...restrict')
insert into sys_full_text_index (id, attribute, weight, object_id, class_id, body) values (9, 'content', 5, 27, 120,' ... restrict')