INSERT INTO `sys_full_text_index` VALUES (1, 'content', 5, 20, 100,'wow wow база данных wow wow база данных wow wow база данных wow wow база данных wow wow база данных')
INSERT INTO `sys_full_text_index` VALUES (2, 'title', 10, 20, 100,'wow wow')
INSERT INTO `sys_full_text_index` VALUES (3, 'content', 5, 21, 110,'DBMS stands for DataBase ... wow')
INSERT INTO `sys_full_text_index` VALUES (4, 'content', 5, 22, 110,'After you went through a ...')
INSERT INTO `sys_full_text_index` VALUES (5, 'content', 5, 23, 110,'In this tutorial we will show ...')
INSERT INTO `sys_full_text_index` VALUES (6, 'content', 5, 24, 110,'1. Never run mysqld as root. 2. ...')
INSERT INTO `sys_full_text_index` VALUES (7, 'content', 5, 25, 110,'In the following database comparison ...')
INSERT INTO `sys_full_text_index` VALUES (8, 'content', 5, 26, 100,'When configured properly, MySQL ...')